CREATE TABLE "acquereurs" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"prenom" text NOT NULL,
	"nom" text NOT NULL,
	"email" text NOT NULL,
	"telephone" text NOT NULL,
	"budget_min" integer NOT NULL,
	"budget_max" integer NOT NULL,
	"criteres" text[] DEFAULT '{}' NOT NULL,
	"stade_projet" text DEFAULT 'decouverte' NOT NULL,
	"notes" text DEFAULT '' NOT NULL,
	"date_premiere_contact" date NOT NULL,
	"pieces_min" integer,
	"surface_min" real,
	"accessibilite_requise" boolean,
	"necessite_parking" boolean,
	"necessite_exterieur" boolean,
	"cree_le" timestamp with time zone DEFAULT now() NOT NULL,
	"modifie_le" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "acquereurs_stade_projet_check" CHECK ("acquereurs"."stade_projet" IN ('decouverte','recherche_active','offre','compromis','acte'))
);
--> statement-breakpoint
CREATE TABLE "biens" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"reference" text NOT NULL,
	"titre" text NOT NULL,
	"type" text NOT NULL,
	"adresse" text NOT NULL,
	"ville" text NOT NULL,
	"code_postal" text NOT NULL,
	"surface" real NOT NULL,
	"pieces" integer NOT NULL,
	"prix" integer NOT NULL,
	"statut_mandat" text DEFAULT 'actif' NOT NULL,
	"date_mandat" date NOT NULL,
	"caracteristiques" text[] DEFAULT '{}' NOT NULL,
	"description" text DEFAULT '' NOT NULL,
	"etage" integer,
	"ascenseur" boolean,
	"parking" boolean,
	"exterieur" text,
	"cree_le" timestamp with time zone DEFAULT now() NOT NULL,
	"modifie_le" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "biens_type_check" CHECK ("biens"."type" IN ('appartement','maison','studio','loft','local_commercial')),
	CONSTRAINT "biens_statut_mandat_check" CHECK ("biens"."statut_mandat" IN ('actif','suspendu','expire')),
	CONSTRAINT "biens_exterieur_check" CHECK ("biens"."exterieur" IS NULL OR "biens"."exterieur" IN ('aucun','balcon','terrasse','jardin'))
);
